[View in Colaboratory](https://colab.research.google.com/github/MrDoga/Acadview_assignments/blob/master/Assingment_7.ipynb)

In [39]:
#Q1 Import the dataset and write a description about the dataset.
from google.colab import files
files.upload()

#This dataset is made by us government. It depicts different countries along with different states and there population. It also tell us about the gdp,literacy rate ,climate,agriculture etc about that particular country

Saving countries of the world.csv to countries of the world.csv

{'countries of the world.csv': b'Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service\n"Afghanistan ","ASIA (EX. NEAR EAST)         ",31056997,647500,"48,0","0,00","23,06","163,07",700,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"\n"Albania ","EASTERN EUROPE                     ",3581655,28748,"124,6","1,26","-4,93","21,52",4500,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"\n"Algeria ","NORTHERN AFRICA                    ",32930091,2381740,"13,8","0,04","-0,39",31,6000,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"\n"American Samoa ","OCEANIA                            ",57794,199,"290,4","58,29","-20,71","9,27",8000,"97,0","259,5",10,15,75,2,"22,46","3,27",,,\n"Andorra ","WESTERN EUROPE                     ",71201,468,"152,1","0,00","6,6","4,05",19000,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",,,\n"Angola ","SUB-SAHARAN AFRICA                 ",12127071,1246700,"9,7","0,13",0,"191,19",1900,"42,0","7,8","2,41","0,24","97,35",,"45,11","24,2","0,096","0,658","0,246"\n"Anguilla ","LATIN AMER. & CARIB    ",13477,102,"132,1","59,80","10,76","21,03",8600,"95,0","460,0",0,0,100,2,"14,17","5,34","0,04","0,18","0,78"\n"Antigua & Barbuda ","LATIN AMER. & CARIB    ",69108,443,"156,0","34,54","-6,15","19,46",11000,"89,0","549,9","18,18","4,55","77,27",2,"16,93","5,37","0,038","0,22","0,743"\n"Argentina ","LATIN AMER. & CARIB    ",39921833,2766890,"14,4","0,18","0,61","15,18",11200,"97,1","220,4","12,31","0,48","87,21",3,"16,73","7,55","0,095","0,358","0,547"\n"Armenia ","C.W. OF IND. STATES ",2976372,29800,"99,9","0,00","-6,47","23,28",3500,"98,6","195,7","17,55","2,3","80,15",4,"12,07","8,23","0,239","0,343","0,418"\n"Aruba ","LATIN AMER. & CARIB    ",71891,193,"372,5","35,49",0,"5,89",28000,"97,0","516,1","10,53",0,"89,47",2,"11,03","6,68","0,004","0,333","0,663"\n"Australia ","OCEANIA                            ",20264082,7686850,"2,6","0,34","3,98","4,69",29000,"100,0","565,5","6,55","0,04","93,41",1,"12,14","7,51","0,038","0,262","0,7"\n"Austria ","WESTERN EUROPE                     ",8192880,83870,"97,7","0,00",2,"4,66",30000,"98,0","452,2","16,91","0,86","82,23",3,"8,74","9,76","0,018","0,304","0,678"\n"Azerbaijan ","C.W. OF IND. STATES ",7961619,86600,"91,9","0,00","-4,9","81,74",3400,"97,0","137,1","19,63","2,71","77,66",1,"20,74","9,75","0,141","0,457","0,402"\n"Bahamas, The ","LATIN AMER. & CARIB    ",303770,13940,"21,8","25,41","-2,2","25,21",16700,"95,6","460,6","0,8","0,4","98,8",2,"17,57","9,05","0,03","0,07","0,9"\n"Bahrain ","NEAR EAST                          ",698585,665,"1050,5","24,21","1,05","17,27",16900,"89,1","281,3","2,82","5,63","91,55",1,"17,8","4,14","0,005","0,387","0,608"\n"Bangladesh ","ASIA (EX. NEAR EAST)         ",147365352,144000,"1023,4","0,40","-0,71","62,6",1900,"43,1","7,3","62,11","3,07","34,82",2,"29,8","8,27","0,199","0,198","0,603"\n"Barbados ","LATIN AMER. & CARIB    ",279912,431,"649,5","22,51","-0,31","12,5",15700,"97,4","481,9","37,21","2,33","60,46",2,"12,71","8,67","0,06","0,16","0,78"\n"Belarus ","C.W. OF IND. STATES ",10293011,207600,"49,6","0,00","2,54","13,37",6100,"99,6","319,1","29,55","0,6","69,85",4,"11,16","14,02","0,093","0,316","0,591"\n"Belgium ","WESTERN EUROPE                     ",10379067,30528,"340,0","0,22","1,23","4,68",29100,"98,0","462,6","23,28","0,4","76,32",3,"10,38","10,27","0,01","0,24","0,749"\n"Belize ","LATIN AMER. & CARIB    ",287730,22966,"12,5","1,68",0,"25,69",4900,"94,1","115,7","2,85","1,71","95,44",2,"28,84","5,72","0,142","0,152","0,612"\n"Benin ","SUB-SAHARAN AFRICA                 ",7862944,112620,"69,8","0,11",0,85,1100,"40,9","9,7","18,08","2,4","79,52",2,"38,85","12,22","0,316","0,138","0,546"\n"Bermuda ","NORTHERN AMERICA                   ",65773,53,"1241,0","194,34","2,49","8,53",36000,"98,0","851,4",20,0,80,2,"11,4","7,74","0,01","0,1","0,89"\n"Bhutan ","ASIA (EX. NEAR EAST)         ",2279723,47000,"48,5","0,00",0,"100,44",1300,"42,2","14,3","3,09","0,43","96,48",2,"33,65","12,7","0,258","0,379","0,363"\n"Bolivia ","LATIN AMER. & CARIB    ",8989046,1098580,"8,2","0,00","-1,32","53,11",2400,"87,2","71,9","2,67","0,19","97,14","1,5","23,3","7,53","0,128","0,352","0,52"\n"Bosnia & Herzegovina ","EASTERN EUROPE                     ",4498976,51129,"88,0","0,04","0,31","21,05",6100,,"215,4","13,6","2,96","83,44",4,"8,77","8,27","0,142","0,308","0,55"\n"Botswana ","SUB-SAHARAN AFRICA                 ",1639833,600370,"2,7","0,00",0,"54,58",9000,"79,8","80,5","0,65","0,01","99,34",1,"23,08","29,5","0,024","0,469","0,507"\n"Brazil ","LATIN AMER. & CARIB    ",188078227,8511965,"22,1","0,09","-0,03","29,61",7600,"86,4","225,3","6,96","0,9","92,15",2,"16,56","6,17","0,084","0,4","0,516"\n"British Virgin Is. ","LATIN AMER. & CARIB    ",23098,153,"151,0","52,29","10,01","18,05",16000,"97,8","506,5",20,"6,67","73,33",2,"14,89","4,42","0,018","0,062","0,92"\n"Brunei ","ASIA (EX. NEAR EAST)         ",379444,5770,"65,8","2,79","3,59","12,61",18600,"93,9","237,2","0,57","0,76","98,67",2,"18,79","3,45","0,036","0,561","0,403"\n"Bulgaria ","EASTERN EUROPE                     ",7385367,110910,"66,6","0,32","-4,58","20,55",7600,"98,6","336,3","40,02","1,92","58,06",3,"9,65","14,27","0,093","0,304","0,603"\n"Burkina Faso ","SUB-SAHARAN AFRICA                 ",13902972,274200,"50,7","0,00",0,"97,57",1100,"26,6","7,0","14,43","0,19","85,38",2,"45,62","15,6","0,322","0,196","0,482"\n"Burma ","ASIA (EX. NEAR EAST)         ",47382633,678500,"69,8","0,28","-1,8","67,24",1800,"85,3","10,1","15,19","0,97","83,84",2,"17,91","9,83","0,564","0,082","0,353"\n"Burundi ","SUB-SAHARAN AFRICA                 ",8090068,27830,"290,7","0,00","-0,06","69,29",600,"51,6","3,4","35,05","14,02","50,93",2,"42,22","13,46","0,463","0,203","0,334"\n"Cambodia ","ASIA (EX. NEAR EAST)         ",13881427,181040,"76,7","0,24",0,"71,48",1900,"69,4","2,6","20,96","0,61","78,43",2,"26,9","9,06","0,35","0,3","0,35"\n"Cameroon ","SUB-SAHARAN AFRICA                 ",17340702,475440,"36,5","0,08",0,"68,26",1800,"79,0","5,7","12,81","2,58","84,61","1,5","33,89","13,47","0,448","0,17","0,382"\n"Canada ","NORTHERN AMERICA                   ",33098932,9984670,"3,3","2,02","5,96","4,75",29800,"97,0","552,2","4,96","0,02","95,02",,"10,78","7,8","0,022","0,294","0,684"\n"Cape Verde ","SUB-SAHARAN AFRICA                 ",420979,4033,"104,4","23,93","-12,07","47,77",1400,"76,6","169,6","9,68","0,5","89,82",3,"24,87","6,55","0,121","0,219","0,66"\n"Cayman Islands ","LATIN AMER. & CARIB    ",45436,262,"173,4","61,07","18,75","8,19",35000,"98,0","836,3","3,85",0,"96,15",2,"12,74","4,89","0,014","0,032","0,954"\n"Central African Rep. ","SUB-SAHARAN AFRICA                 ",4303356,622984,"6,9","0,00",0,91,1100,"51,0","2,3","3,1","0,14","96,76",2,"33,91","18,65","0,55","0,2","0,25"\n"Chad ","SUB-SAHARAN AFRICA                 ",9944201,1284000,"7,7","0,00","-0,11","93,82",1200,"47,5","1,3","2,86","0,02","97,12",2,"45,73","16,38","0,335","0,259","0,406"\n"Chile ","LATIN AMER. & CARIB    ",16134219,756950,"21,3","0,85",0,"8,8",9900,"96,2","213,0","2,65","0,42","96,93",3,"15,23","5,81","0,06","0,493","0,447"\n"China ","ASIA (EX. NEAR EAST)         ",1313973713,9596960,"136,9","0,15","-0,4","24,18",5000,"90,9","266,7","15,4","1,25","83,35","1,5","13,25","6,97","0,125","0,473","0,403"\n"Colombia ","LATIN AMER. & CARIB    ",43593035,1138910,"38,3","0,28","-0,31","20,97",6300,"92,5","176,2","2,42","1,67","95,91",2,"20,48","5,58","0,125","0,342","0,533"\n"Comoros ","SUB-SAHARAN AFRICA                 ",690948,2170,"318,4","15,67",0,"74,93",700,"56,5","24,5","35,87","23,32","40,81",2,"36,93","8,2","0,4","0,04","0,56"\n"Congo, Dem. Rep. ","SUB-SAHARAN AFRICA                 ",62660551,2345410,"26,7","0,00",0,"94,69",700,"65,5","0,2","2,96","0,52","96,52",2,"43,69","13,27","0,55","0,11","0,34"\n"Congo, Repub. of the ","SUB-SAHARAN AFRICA                 ",3702314,342000,"10,8","0,05","-0,17","93,86",700,"83,8","3,7","0,51","0,13","99,36",2,"42,57","12,93","0,062","0,57","0,369"\n"Cook Islands ","OCEANIA                            ",21388,240,"89,1","50,00",,,5000,"95,0","289,9","17,39","13,04","69,57",2,21,,"0,151","0,096","0,753"\n"Costa Rica ","LATIN AMER. & CARIB    ",4075261,51100,"79,8","2,52","0,51","9,95",9100,"96,0","340,7","4,41","5,88","89,71",2,"18,32","4,36","0,088","0,299","0,614"\n"Cote d\'Ivoire ","SUB-SAHARAN AFRICA                 ",17654843,322460,"54,8","0,16","-0,07","90,83",1400,"50,9","14,6","9,75","13,84","76,41",2,"35,11","14,84","0,279","0,171","0,55"\n"Croatia ","EASTERN EUROPE                     ",4494749,56542,"79,5","10,32","1,58","6,84",10600,"98,5","420,4","26,09","2,27","71,65",,"9,61","11,48","0,07","0,308","0,622"\n"Cuba ","LATIN AMER. & CARIB    ",11382820,110860,"102,7","3,37","-1,58","6,33",2900,"97,0","74,7","33,05","7,6","59,35",2,"11,89","7,22","0,055","0,261","0,684"\n"Cyprus ","NEAR EAST                          ",784301,9250,"84,8","7,01","0,43","7,18",19200,"97,6",,"7,79","4,44","87,77",3,"12,56","7,68","0,037","0,198","0,765"\n"Czech Republic ","EASTERN EUROPE                     ",10235455,78866,"129,8","0,00","0,97","3,93",15700,"99,9","314,3","39,8","3,05","57,15",3,"9,02","10,59","0,034","0,393","0,573"\n"Denmark ","WESTERN EUROPE                     ",5450661,43094,"126,5","16,97","2,48","4,56",31100,"100,0","614,6","54,02","0,19","45,79",3,"11,13","10,36","0,018","0,246","0,735"\n"Djibouti ","SUB-SAHARAN AFRICA                 ",486530,23000,"21,2","1,37",0,"104,13",1300,"67,9","22,8","0,04",0,"99,96",1,"39,53","19,31","0,179","0,225","0,596"\n"Dominica ","LATIN AMER. & CARIB    ",68910,754,"91,4","19,63","-13,87","14,15",5400,"94,0","304,8","6,67",20,"73,33",2,"15,27","6,73","0,177","0,328","0,495"\n"Dominican Republic ","LATIN AMER. & CARIB    ",9183984,48730,"188,5","2,64","-3,22","32,38",6000,"84,7","97,4","22,65","10,33","67,02",2,"23,22","5,73","0,112","0,306","0,582"\n"East Timor ","ASIA (EX. NEAR EAST)         ",1062777,15007,"70,8","4,70",0,"47,41",500,"58,6",,"4,71","0,67","94,62",2,"26,99","6,24","0,085","0,231","0,684"\n"Ecuador ","LATIN AMER. & CARIB    ",13547510,283560,"47,8","0,79","-8,58","23,66",3300,"92,5","125,6","5,85","4,93","89,22",2,"22,29","4,23","0,07","0,312","0,618"\n"Egypt ","NORTHERN AFRICA                    ",78887007,1001450,"78,8","0,24","-0,22","32,59",4000,"57,7","131,8","2,87","0,48","96,65",1,"22,94","5,23","0,149","0,357","0,493"\n"El Salvador ","LATIN AMER. & CARIB    ",6822378,21040,"324,3","1,46","-3,74","25,1",4800,"80,2","142,4","31,85","12,07","56,08",2,"26,61","5,78","0,099","0,302","0,599"\n"Equatorial Guinea ","SUB-SAHARAN AFRICA                 ",540109,28051,"19,3","1,06",0,"85,13",2700,"85,7","18,5","4,63","3,57","91,8",2,"35,59","15,06","0,03","0,906","0,062"\n"Eritrea ","SUB-SAHARAN AFRICA                 ",4786994,121320,"39,5","1,84",0,"74,87",700,"58,6","7,9","4,95","0,03","95,02","1,5","34,33","9,6","0,102","0,254","0,643"\n"Estonia ","BALTICS                            ",1324333,45226,"29,3","8,39","-3,16","7,87",12300,"99,8","333,8","16,04","0,45","83,51",3,"10,04","13,25","0,04","0,294","0,666"\n"Ethiopia ","SUB-SAHARAN AFRICA                 ",74777981,1127127,"66,3","0,00",0,"95,32",700,"42,7","8,2","10,71","0,75","88,54",2,"37,98","14,86","0,475","0,099","0,426"\n"Faroe Islands ","WESTERN EUROPE                     ",47246,1399,"33,8","79,84","1,41","6,24",22000,,"503,8","2,14",0,"97,86",,"14,05","8,7","0,27","0,11","0,62"\n"Fiji ","OCEANIA                            ",905949,18270,"49,6","6,18","-3,14","12,62",5800,"93,7","112,6","10,95","4,65","84,4",2,"22,55","5,65","0,089","0,135","0,776"\n"Finland ","WESTERN EUROPE                     ",5231372,338145,"15,5","0,37","0,95","3,57",27400,"100,0","405,3","7,19","0,03","92,78",3,"10,45","9,86","0,028","0,295","0,676"\n"France ","WESTERN EUROPE                     ",60876136,547030,"111,3","0,63","0,66","4,26",27600,"99,0","586,4","33,53","2,07","64,4",4,"11,99","9,14","0,022","0,214","0,764"\n"French Guiana ","LATIN AMER. & CARIB    ",199509,91000,"2,2","0,42","6,27","12,07",8300,"83,0","255,6","0,14","0,05","99,81",2,"20,46","4,88","0,066","0,156","0,778"\n"French Polynesia ","OCEANIA                            ",274578,4167,"65,9","60,60","2,94","8,44",17500,"98,0","194,5","0,82","5,46","93,72",2,"16,68","4,69","0,031","0,19","0,769"\n"Gabon ","SUB-SAHARAN AFRICA                 ",1424906,267667,"5,3","0,33",0,"53,64",5500,"63,2","27,4","1,26","0,66","98,08",2,"36,16","12,25","0,061","0,592","0,348"\n"Gambia, The ","SUB-SAHARAN AFRICA                 ",1641564,11300,"145,3","0,71","1,57","72,02",1700,"40,1","26,8",25,"0,5","74,5",2,"39,37","12,25","0,308","0,142","0,549"\n"Gaza Strip ","NEAR EAST                          ",1428757,360,"3968,8","11,11","1,6","22,93",600,,"244,3","28,95","21,05",50,3,"39,45","3,8","0,03","0,283","0,687"\n"Georgia ","C.W. OF IND. STATES ",4661473,69700,"66,9","0,44","-4,7","18,59",2500,"99,0","146,6","11,44","3,86","84,7",3,"10,41","9,23","0,172","0,275","0,553"\n"Germany ","WESTERN EUROPE                     ",82422299,357021,"230,9","0,67","2,18","4,16",27600,"99,0","667,9","33,85","0,59","65,56",3,"8,25","10,62","0,009","0,296","0,695"\n"Ghana ","SUB-SAHARAN AFRICA                 ",22409572,239460,"93,6","0,23","-0,64","51,43",2200,"74,8","14,4","16,26","9,67","74,07",2,"30,52","9,72","0,366","0,246","0,387"\n"Gibraltar ","WESTERN EUROPE                     ",27928,7,"3989,7","171,43",0,"5,13",17500,,"877,7",0,0,100,,"10,74","9,31",,,\n"Greece ","WESTERN EUROPE                     ",10688058,131940,"81,0","10,37","2,35","5,53",20000,"97,5","589,7","21,1","8,78","70,12",3,"9,68","10,24","0,054","0,213","0,733"\n"Greenland ","NORTHERN AMERICA                   ",56361,2166086,"0,0","2,04","-8,37","15,82",20000,,"448,9",0,0,100,1,"15,93","7,84",,,\n"Grenada ","LATIN AMER. & CARIB    ",89703,344,"260,8","35,17","-13,92","14,62",5000,"98,0","364,5","5,88","29,41","64,71",2,"22,08","6,88","0,054","0,18","0,766"\n"Guadeloupe ","LATIN AMER. & CARIB    ",452776,1780,"254,4","17,19","-0,15","8,6",8000,"90,0","463,8","11,24","3,55","85,21",2,"15,05","6,09","0,15","0,17","0,68"\n"Guam ","OCEANIA                            ",171019,541,"316,1","23,20",0,"6,94",21000,"99,0","492,0","9,09","16,36","74,55",2,"18,79","4,48",,,\n"Guatemala ","LATIN AMER. & CARIB    ",12293545,108890,"112,9","0,37","-1,67","35,93",4100,"70,6","92,1","12,54","5,03","82,43",2,"29,88","5,2","0,227","0,188","0,585"\n"Guernsey ","WESTERN EUROPE                     ",65409,78,"838,6","64,10","3,84","4,71",20000,,"842,4",,,,3,"8,81","10,01","0,03","0,1","0,87"\n"Guinea ","SUB-SAHARAN AFRICA                 ",9690222,245857,"39,4","0,13","-3,06","90,37",2100,"35,9","2,7","3,63","2,58","93,79",2,"41,76","15,48","0,237","0,362","0,401"\n"Guinea-Bissau ","SUB-SAHARAN AFRICA                 ",1442029,36120,"39,9","0,97","-1,57","107,17",800,"42,4","7,4","10,67","8,82","80,51",2,"37,22","16,53","0,62","0,12","0,26"\n"Guyana ","LATIN AMER. & CARIB    ",767245,214970,"3,6","0,21","-2,07","33,26",4000,"98,8","143,5","2,44","0,15","97,41",2,"18,28","8,28","0,37","0,203","0,427"\n"Haiti ","LATIN AMER. & CARIB    ",8308504,27750,"299,4","6,38","-3,4","73,45",1600,"52,9","16,9","28,3","11,61","60,09",2,"36,44","12,17","0,28","0,2","0,52"\n"Honduras ","LATIN AMER. & CARIB    ",7326496,112090,"65,4","0,73","-1,99","29,32",2600,"76,2","67,5","9,55","3,22","87,23",2,"28,24","5,28","0,139","0,312","0,549"\n"Hong Kong ","ASIA (EX. NEAR EAST)         ",6940432,1092,"6355,7","67,12","5,24","2,97",28800,"93,5","546,7","5,05","1,01","93,94",2,"7,29","6,29","0,001","0,092","0,906"\n"Hungary ","EASTERN EUROPE                     ",9981334,93030,"107,3","0,00","0,86","8,57",13900,"99,4","336,2","50,09","2,06","47,85",3,"9,72","13,11","0,037","0,312","0,651"\n"Iceland ","WESTERN EUROPE                     ",299388,103000,"2,9","4,83","2,38","3,31",30900,"99,9","647,7","0,07",0,"99,93",3,"13,64","6,72","0,086","0,15","0,765"\n"India ","ASIA (EX. NEAR EAST)         ",1095351995,3287590,"333,2","0,21","-0,07","56,29",2900,"59,5","45,4","54,4","2,74","42,86","2,5","22,01","8,18","0,186","0,276","0,538"\n"Indonesia ","ASIA (EX. NEAR EAST)         ",245452739,1919440,"127,9","2,85",0,"35,6",3200,"87,9","52,0","11,32","7,23","81,45",2,"20,34","6,25","0,134","0,458","0,408"\n"Iran ","ASIA (EX. NEAR EAST)         ",68688433,1648000,"41,7","0,15","-0,84","41,58",7000,"79,4","276,4","8,72","1,39","89,89",1,17,"5,55","0,116","0,424","0,46"\n"Iraq ","NEAR EAST                          ",26783383,437072,"61,3","0,01",0,"50,25",1500,"40,4","38,6","13,15","0,78","86,07",1,"31,98","5,37","0,073","0,666","0,261"\n"Ireland ","WESTERN EUROPE                     ",4062235,70280,"57,8","2,06","4,99","5,39",29600,"98,0","500,5","15,2","0,03","84,77",3,"14,45","7,82","0,05","0,46","0,49"\n"Isle of Man ","WESTERN EUROPE                     ",75441,572,"131,9","27,97","5,36","5,93",21000,,"676,0",9,0,91,3,"11,05","11,19","0,01","0,13","0,86"\n"Israel ","NEAR EAST                          ",6352117,20770,"305,8","1,31","0,68","7,03",19800,"95,4","462,3","16,39","4,17","79,44",3,"17,97","6,18","0,026","0,317","0,657"\n"Italy ","WESTERN EUROPE                     ",58133509,301230,"193,0","2,52","2,07","5,94",26700,"98,6","430,9","27,79","9,53","62,68",,"8,72","10,4","0,021","0,291","0,688"\n"Jamaica ","LATIN AMER. & CARIB    ",2758124,10991,"250,9","9,30","-4,92","12,36",3900,"87,9","124,0","16,07","10,16","73,77",2,"20,82","6,52","0,049","0,337","0,615"\n"Japan ","ASIA (EX. NEAR EAST)         ",127463611,377835,"337,4","7,87",0,"3,26",28200,"99,0","461,2","12,19","0,96","86,85",3,"9,37","9,16","0,017","0,258","0,725"\n"Jersey ","WESTERN EUROPE                     ",91084,116,"785,2","60,34","2,76","5,24",24800,,"811,3",0,0,100,3,"9,3","9,28","0,05","0,02","0,93"\n"Jordan ","NEAR EAST                          ",5906760,92300,"64,0","0,03","6,59","17,35",4300,"91,3","104,5","2,67","1,83","95,5",1,"21,25","2,65","0,033","0,287","0,68"\n"Kazakhstan ","C.W. OF IND. STATES ",15233244,2717300,"5,6","0,00","-3,35","29,21",6300,"98,4","164,1","7,98","0,05","91,97",4,16,"9,42","0,067","0,386","0,547"\n"Kenya ","SUB-SAHARAN AFRICA                 ",34707817,582650,"59,6","0,09","-0,1","61,47",1000,"85,1","8,1","8,08","0,98","90,94","1,5","39,72","14,02","0,163","0,188","0,651"\n"Kiribati ","OCEANIA                            ",105432,811,"130,0","140,94",0,"48,52",800,,"42,7","2,74","50,68","46,58",2,"30,65","8,26","0,089","0,242","0,668"\n"Korea, North ","ASIA (EX. NEAR EAST)         ",23113019,120540,"191,8","2,07",0,"24,04",1300,"99,0","42,4","20,76","2,49","76,75",3,"15,54","7,13","0,3","0,34","0,36"\n"Korea, South ","ASIA (EX. NEAR EAST)         ",48846823,98480,"496,0","2,45",0,"7,05",17800,"97,9","486,1","17,18","1,95","80,87",3,10,"5,85","0,033","0,403","0,563"\n"Kuwait ","NEAR EAST                          ",2418393,17820,"135,7","2,80","14,18","9,95",19000,"83,5","211,0","0,73","0,11","99,16",1,"21,94","2,41","0,004","0,479","0,516"\n"Kyrgyzstan ","C.W. OF IND. STATES ",5213898,198500,"26,3","0,00","-2,45","35,64",1600,"97,0","84,0","7,3","0,35","92,35","2,5","22,8","7,08","0,353","0,208","0,439"\n"Laos ","ASIA (EX. NEAR EAST)         ",6368481,236800,"26,9","0,00",0,"85,22",1700,"66,4","14,1","3,8","0,35","95,85",2,"35,49","11,55","0,455","0,287","0,258"\n"Latvia ","BALTICS                            ",2274735,64589,"35,2","0,82","-2,23","9,55",10200,"99,8","321,4","29,67","0,47","69,86",3,"9,24","13,66","0,04","0,261","0,699"\n"Lebanon ","NEAR EAST                          ",3874050,10400,"372,5","2,16",0,"24,52",4800,"87,4","255,6","16,62","13,98","69,4",,"18,52","6,21","0,12","0,21","0,67"\n"Lesotho ","SUB-SAHARAN AFRICA                 ",2022331,30355,"66,6","0,00","-0,74","84,23",3000,"84

In [40]:
import pandas as pd 
c=pd.read_csv("countries of the world.csv")
c.head(5)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [41]:
c.describe()

         Population  Area (sq. mi.)  GDP ($ per capita)
count  2.270000e+02    2.270000e+02          226.000000
mean   2.874028e+07    5.982270e+05         9689.823009
std    1.178913e+08    1.790282e+06        10049.138513
min    7.026000e+03    2.000000e+00          500.000000
25%    4.376240e+05    4.647500e+03         1900.000000
50%    4.786994e+06    8.660000e+04         5550.000000
75%    1.749777e+07    4.418110e+05        15700.000000
max    1.313974e+09    1.707520e+07        55100.000000

In [42]:
#Q2. Find the count of the missing values and describe how you have handled the missing data.
m=c.dropna()
m

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
6,Anguilla,LATIN AMER. & CARIB,13477,102,"132,1","59,80","10,76","21,03",8600.0,"95,0","460,0",0,0,100,2,"14,17","5,34","0,04","0,18","0,78"
7,Antigua & Barbuda,LATIN AMER. & CARIB,69108,443,"156,0","34,54","-6,15","19,46",11000.0,"89,0","549,9","18,18","4,55","77,27",2,"16,93","5,37","0,038","0,22","0,743"
8,Argentina,LATIN AMER. & CARIB,39921833,2766890,"14,4","0,18","0,61","15,18",11200.0,"97,1","220,4","12,31","0,48","87,21",3,"16,73","7,55","0,095","0,358","0,547"
9,Armenia,C.W. OF IND. STATES,2976372,29800,"99,9","0,00","-6,47","23,28",3500.0,"98,6","195,7","17,55","2,3","80,15",4,"12,07","8,23","0,239","0,343","0,418"
10,Aruba,LATIN AMER. & CARIB,71891,193,"372,5","35,49",0,"5,89",28000.0,"97,0","516,1","10,53",0,"89,47",2,"11,03","6,68","0,004","0,333","0,663"
11,Australia,OCEANIA,20264082,7686850,"2,6","0,34","3,98","4,69",29000.0,"100,0","565,5","6,55","0,04","93,41",1,"12,14","7,51","0,038","0,262","0,7"
12,Austria,WESTERN EUROPE,8192880,83870,"97,7","0,00",2,"4,66",30000.0,"98,0","452,2","16,91","0,86","82,23",3,"8,74","9,76","0,018","0,304","0,678"
13,Azerbaijan,C.W. OF IND. STATES,7961619,86600,"91,9","0,00","-4,9","81,74",3400.0,"97,0","137,1","19,63","2,71","77,66",1,"20,74","9,75","0,141","0,457","0,402"
14,"Bahamas, The",LATIN AMER. & CARIB,303770,13940,"21,8","25,41","-2,2","25,21",16700.0,"95,6","460,6","0,8","0,4","98,8",2,"17,57","9,05","0,03","0,07","0,9"
15,Bahrain,NEAR EAST,698585,665,"1050,5","24,21","1,05","17,27",16900.0,"89,1","281,3","2,82","5,63","91,55",1,"17,8","4,14","0,005","0,387","0,608"
16,Bangladesh,ASIA (EX. NEAR EAST),147365352,144000,"1023,4","0,40","-0,71","62,6",1900.0,"43,1","7,3","62,11","3,07","34,82",2,"29,8","8,27","0,199","0,198","0,603"
17,Barbados,LATIN AMER. & CARIB,279912,431,"649,5","22,51","-0,31","12,5",15700.0,"97,4","481,9","37,21","2,33","60,46",2,"12,71","8,67","0,06","0,16","0,78"
18,Belarus,C.W. OF IND. STATES,10293011,207600,"49,6","0,00","2,54","13,37",6100.0,"99,6","319,1","29,55","0,6","69,85",4,"11,16","14,02","0,093","0,316","0,591"
19,Belgium,WESTERN EUROPE,10379067,30528,"340,0","0,22","1,23","4,68",29100.0,"98,0","462,6","23,28","0,4","76,32",3,"10,38","10,27","0,01","0,24","0,749"
20,Belize,LATIN AMER. & CARIB,287730,22966,"12,5","1,68",0,"25,69",4900.0,"94,1","115,7","2,85","1,71","95,44",2,"28,84","5,72","0,142","0,152","0,612"
21,Benin,SUB-SAHARAN AFRICA,7862944,112620,"69,8","0,11",0,85,1100.0,"40,9","9,7","18,08","2,4","79,52",2,"38,85","12,22","0,316","0,138","0,546"
22,Bermuda,NORTHERN AMERICA,65773,53,"1241,0","194,34","2,49","8,53",36000.0,"98,0","851,4",20,0,80,2,"11,4","7,74","0,01","0,1","0,89"
23,Bhutan,ASIA (EX. NEAR EAST),2279723,47000,"48,5","0,00",0,"100,44",1300.0,"42,2","14,3","3,09","0,43","96,48",2,"33,65","12,7","0,258","0,379","0,363"
24,Bolivia,LATIN AMER. & CARIB,8989046,1098580,"8,2","0,00","-1,32","53,11",2400.0,"87,2","71,9","2,67","0,19","97,14","1,5","23,3","7,53","0,128","0,352","0,52"
26,Botswana,SUB-SAHARAN AFRICA,1639833,600370,"2,7","0,00",0,"54,58",9000.0,"79,8","80,5","0,65","0,01","99,34",1,"23,08","29,5","0,024","0,469","0,507"
27,Brazil,LATIN AMER. & CARIB,188078227,8511965,"22,1","0,09","-0,03","29,61",7600.0,"86,4","225,3","6,96","0,9","92,15",2,"16,56","6,17","0,084","0,4","0,516"
28,British Virgin Is.,LATIN AMER. & CARIB,23098,153,"151,0","52,29","10,01","18,05",16000.0,"97,8","506,5",20,"6,67","73,33",2,"14,89","4,42","0,018","0,062","0,92"
29,Brunei,ASIA (EX. NEAR EAST),379444,5770,"65,8","2,79","3,59","12,61",18600.0,"93,9","237,2","0,57","0,76","98,67",2,"18,79","3,45","0,036","0,561","0,403"
30,Bulgaria,EASTERN EUROPE,7385367,110910,"66,6","0,32","-4,58","20,55",7600.0,"98,6","336,3","40,02","1,92","58,06",3,"9,65","14,27","0,093","0,304","0,603"
31,Burkina Faso,SUB-SAHARAN AFRICA,13902972,274200,"50,7","0,00",0,"97,57",1100.0,"26,6","7,0","14,43","0,19","85,38",2,"45,62","15,6","0,322","0,196","0,482"
32,Burma,ASIA (EX. NEAR EAST),47382633,678500,"69,8","0,28","-1,8","67,24",1800.0,"85,3","10,1","15,19","0,97","83,84",2,"17,91","9,83","0,564","0,082","0,353"
33,Burundi,SUB-SAHARAN AFRICA,8090068,27830,"290,7","0,00","-0,06","69,29",600.0,"51,6","3,4","35,05","14,02","50,93",2,"42,22","13,46","0,463","0,203","0,334"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Spain,WESTERN EUROPE,40397842,504782,"80,0","0,98","0,99","4,42",22000.0,"97,9","453,5","26,07","9,87","64,06",3,"10,06","9,72","0,04","0,295","0,665"
191,Sri Lanka,ASIA (EX. NEAR EAST),20222240,65610,"308,2","2,04","-1,31","14,35",3700.0,"92,3","61,5","13,86","15,7","70,44",2,"15,51","6,52","0,178","0,276","0,545"
192,Sudan,SUB-SAHARAN AFRICA,41236378,2505810,"16,5","0,03","-0,02","62,5",1900.0,"61,1","16,3","6,83","0,18","92,99",2,"34,53","8,97","0,387","0,203","0,41"
193,Suriname,LATIN AMER. & CARIB,439117,163270,"2,7","0,24","-8,81","23,57",4000.0,"93,0","184,7","0,37","0,06","99,57",2,"18,02","7,27","0,13","0,22","0,65"
194,Swaziland,SUB-SAHARAN AFRICA,1136334,17363,"65,5","0,00",0,"69,27",4900.0,"81,6","30,8","10,35","0,7","88,95","2,5","27,41","29,74","0,119","0,515","0,366"
195,Sweden,WESTERN EUROPE,9016596,449964,"20,0","0,72","1,67","2,77",26800.0,"99,0","715,0","6,54","0,01","93,45",3,"10,27","10,31","0,011","0,282","0,707"
196,Switzerland,WESTERN EUROPE,7523934,41290,"182,2","0,00","4,05","4,39",32700.0,"99,0","680,9","10,42","0,61","88,97",3,"9,71","8,49","0,015","0,34","0,645"
197,Syria,NEAR EAST,18881361,185180,"102,0","0,10",0,"29,53",3300.0,"76,9","153,8","25,22","4,43","70,35",1,"27,76","4,81","0,249","0,23","0,519"
198,Taiwan,ASIA (EX. NEAR EAST),23036087,35980,"640,3","4,35",0,"6,4",23400.0,"96,1","591,0",24,1,75,2,"12,56","6,48","0,018","0,259","0,723"
199,Tajikistan,C.W. OF IND. STATES,7320815,143100,"51,2","0,00","-2,86","110,76",1000.0,"99,4","33,5","6,61","0,92","92,47",2,"32,65","8,25","0,234","0,286","0,48"
201,Thailand,ASIA (EX. NEAR EAST),64631595,514000,"125,7","0,63",0,"20,48",7400.0,"92,6","108,9","29,36","6,46","64,18",2,"13,87","7,04","0,099","0,441","0,46"
202,Togo,SUB-SAHARAN AFRICA,5548702,56785,"97,7","0,10",0,"66,61",1500.0,"60,9","10,6","46,15","2,21","51,64",2,"37,01","9,83","0,395","0,204","0,401"
203,Tonga,OCEANIA,114689,748,"153,3","56,02",0,"12,62",2200.0,"98,5","97,7","23,61","43,06","33,33",2,"25,37","5,28","0,23","0,27","0,5"
204,Trinidad & Tobago,LATIN AMER. & CARIB,1065842,5128,"207,9","7,06","-10,83","24,31",9500.0,"98,6","303,5","14,62","9,16","76,22",2,"12,9","10,57","0,007","0,57","0,423"
205,Tunisia,NORTHERN AFRICA,10175014,163610,"62,2","0,70","-0,57","24,77",6900.0,"74,2","123,6","17,86","13,74","68,4",3,"15,52","5,13","0,132","0,318","0,55"
206,Turkey,NEAR EAST,70413958,780580,"90,2","0,92",0,"41,04",6700.0,"86,5","269,5","30,93","3,31","65,76",3,"16,62","5,97","0,117","0,298","0,585"
207,Turkmenistan,C.W. OF IND. STATES,5042920,488100,"10,3","0,00","-0,86","73,08",5800.0,"98,0","74,6","3,72","0,14","96,14",1,"27,61","8,6","0,209","0,38","0,411"
210,Uganda,SUB-SAHARAN AFRICA,28195754,236040,"119,5","0,00",0,"67,83",1400.0,"69,9","3,6","25,88","10,65","63,47",2,"47,35","12,24","0,311","0,222","0,469"
211,Ukraine,C.W. OF IND. STATES,46710816,603700,"77,4","0,46","-0,39","20,34",5400.0,"99,7","259,9","56,21","1,61","42,18",3,"8,82","14,39","0,187","0,452","0,361"
212,United Arab Emirates,NEAR EAST,2602713,82880,"31,4","1,59","1,03","14,51",23200.0,"77,9","475,3","0,6","2,25","97,15",1,"18,96","4,4","0,04","0,585","0,375"
213,United Kingdom,WESTERN EUROPE,60609153,244820,"247,6","5,08","2,19","5,16",27700.0,"99,0","543,5","23,46","0,21","76,33",3,"10,71","10,13","0,005","0,237","0,758"
214,United States,NORTHERN AMERICA,298444215,9631420,"31,0","0,21","3,41","6,5",37800.0,"97,0","898,0","19,13","0,22","80,65",3,"14,14","8,26","0,01","0,204","0,787"
215,Uruguay,LATIN AMER. & CARIB,3431932,176220,"19,5","0,37","-0,32","11,95",12800.0,"98,0","291,4","7,43","0,23","92,34",3,"13,91","9,05","0,093","0,311","0,596"
216,Uzbekistan,C.W. OF IND. STATES,27307134,447400,"61,0","0,00","-1,72","71,1",1700.0,"99,3","62,9","10,83","0,83","88,34",1,"26,36","7,84","0,342","0,229","0,43"
217,Vanuatu,OCEANIA,208869,12200,"17,1","20,72",0,"55,16",2900.0,"53,0","32,6","2,46","7,38","90,16",2,"22,72","7,82","0,26","0,12","0,62"
218,Venezuela,LATIN AMER. & CARIB,25730435,912050,"28,2","0,31","-0,04","22,2",4800.0,"93,4","140,1","2,95","0,92","96,13",2,"18,71","4,92","0,04","0,419","0,541"
219,Vietnam,ASIA (EX. NEAR EAST),84402966,329560,"256,1","1,05","-0,45","25,95",2500.0,"90,3","187,7","19,97","5,95","74,08",2,"16,86","6,22","0,209","0,41","0,381"
224,Yemen,NEAR EAST,21456188,527970,"40,6","0,36",0,"61,5",800.0,"50,2","37,2","2,78","0,24","96,98",1,"42,89","8,3","0,135","0,472","0,393"
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,"15,3","0,00",0,"88,29",800.0,"80,6","8,2","7,08","0,03","92,9",2,41,"19,93","0,22","0,29","0,489"
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,"31,3","0,00",0,"67,69",1900.0,"90,7","26,8","8,32","0,34","91,34",2,"28,01","21,84","0,179","0,243","0,579"

In [52]:
pd.crosstab(c['Population'],c['Region'],margins=True)

Region,ASIA (EX. NEAR EAST),BALTICS,C.W. OF IND. STATES,EASTERN EUROPE,LATIN AMER. & CARIB,NEAR EAST,NORTHERN AFRICA,NORTHERN AMERICA,OCEANIA,SUB-SAHARAN AFRICA,WESTERN EUROPE,All
Population,,,,,,,,,,,,
7026,0,0,0,0,0,0,0,1,0,0,0,1
7502,0,0,0,0,0,0,0,0,0,1,0,1
9439,0,0,0,0,1,0,0,0,0,0,0,1
11810,0,0,0,0,0,0,0,0,1,0,0,1
13287,0,0,0,0,0,0,0,0,1,0,0,1
13477,0,0,0,0,1,0,0,0,0,0,0,1
16025,0,0,0,0,0,0,0,0,1,0,0,1
20579,0,0,0,0,0,0,0,0,1,0,0,1
21152,0,0,0,0,1,0,0,0,0,0,0,1
21388,0,0,0,0,0,0,0,0,1,0,0,1
23098,0,0,0,0,1,0,0,0,0,0,0,1
27928,0,0,0,0,0,0,0,0,0,0,1,1
29251,0,0,0,0,0,0,0,0,0,0,1,1
32543,0,0,0,0,0,0,0,0,0,0,1,1
33987,0,0,0,0,0,0,0,0,0,0,1,1
39129,0,0,0,0,1,0,0,0,0,0,0,1
45436,0,0,0,0,1,0,0,0,0,0,0,1
47246,0,0,0,0,0,0,0,0,0,0,1,1
56361,0,0,0,0,0,0,0,1,0,0,0,1
57794,0,0,0,0,0,0,0,0,1,0,0,1
60422,0,0,0,0,0,0,0,0,1,0,0,1
65409,0,0,0,0,0,0,0,0,0,0,1,1
65773,0,0,0,0,0,0,0,1,0,0,0,1
68910,0,0,0,0,1,0,0,0,0,0,0,1
69108,0,0,0,0,1,0,0,0,0,0,0,1
71201,0,0,0,0,0,0,0,0,0,0,1,1
71891,0,0,0,0,1,0,0,0,0,0,0,1
75441,0,0,0,0,0,0,0,0,0,0,1,1
81541,0,0,0,0,0,0,0,0,0,1,0,1
82459,0,0,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
41236378,0,0,0,0,0,0,0,0,0,1,0,1
43593035,0,0,0,0,1,0,0,0,0,0,0,1
44187637,0,0,0,0,0,0,0,0,0,1,0,1
46710816,0,0,1,0,0,0,0,0,0,0,0,1
47382633,1,0,0,0,0,0,0,0,0,0,0,1
48846823,1,0,0,0,0,0,0,0,0,0,0,1
58133509,0,0,0,0,0,0,0,0,0,0,1,1
60609153,0,0,0,0,0,0,0,0,0,0,1,1
60876136,0,0,0,0,0,0,0,0,0,0,1,1
62660551,0,0,0,0,0,0,0,0,0,1,0,1
64631595,1,0,0,0,0,0,0,0,0,0,0,1
68688433,1,0,0,0,0,0,0,0,0,0,0,1
70413958,0,0,0,0,0,1,0,0,0,0,0,1
74777981,0,0,0,0,0,0,0,0,0,1,0,1
78887007,0,0,0,0,0,0,1,0,0,0,0,1
82422299,0,0,0,0,0,0,0,0,0,0,1,1
84402966,1,0,0,0,0,0,0,0,0,0,0,1
89468677,1,0,0,0,0,0,0,0,0,0,0,1
107449525,0,0,0,0,1,0,0,0,0,0,0,1
127463611,1,0,0,0,0,0,0,0,0,0,0,1
131859731,0,0,0,0,0,0,0,0,0,1,0,1
142893540,0,0,1,0,0,0,0,0,0,0,0,1
147365352,1,0,0,0,0,0,0,0,0,0,0,1
165803560,1,0,0,0,0,0,0,0,0,0,0,1
188078227,0,0,0,0,1,0,0,0,0,0,0,1
245452739,1,0,0,0,0,0,0,0,0,0,0,1
298444215,0,0,0,0,0,0,0,1,0,0,0,1
1095351995,1,0,0,0,0,0,0,0,0,0,0,1
1313973713,1,0,0,0,0,0,0,0,0,0,0,1
All,28,3,12,12,45,16,6,5,21,51,28,227

In [0]:
import matplotlib.pyplot as plt 
import seaborn as sns
plt.rcParams['figure.figsize']=(8,6)
sns.countplot(x='Country',hue='Service',data='c')